# Generated by Django 4.0.3 on 2022-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='image',
        ),
    ]
